---
title: "media_franchises"
author: "Sam Taylor"
date: "08/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
# load packages
library(tidyverse)
library(broom)

# load data
media_franchises <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")

# data preprocessing
media_franchises_processed <- media_franchises %>% 
                               mutate(decade = 10 * (year_created %/% 10))

```

## What are the most lucrative media franchises

```{r}
# tidy dataset and plot
media_franchises_processed %>% 
  group_by(franchise) %>% 
  summarise(total_revenue = sum(revenue)) %>% 
  arrange(desc(total_revenue)) %>% 
  top_n(10) %>% 
  ggplot(aes(fct_reorder(franchise, total_revenue), total_revenue)) + 
  geom_col(fill='dodgerblue', alpha=1/3, color='black') + 
  scale_y_continuous(labels=dollar_format()) + 
  coord_flip() +
  labs(x='',
       y='Total Revenue (billion dollars)',
       title ='Which media franchises have the highest total revenue')
```

## Which original mediums have the highest revenue

```{r}
# check counts of different types of media - NB. doesn't take into account multiple sources associated. 
media_franchises_processed %>% 
  group_by(original_media) %>% 
  count(sort=T)

# plot the data accordingly
media_franchises_processed %>% 
  mutate(original_media = fct_lump(original_media, 6)) %>% 
  ggplot(aes(x=fct_reorder(original_media, revenue), y=revenue)) + 
    geom_boxplot() +
    coord_flip() +
  scale_y_continuous(labels=dollar_format())  +
  labs(x='',
       y='Total Revenue (billion dollars)',
       title ='Which original mediums have the highest total revenue ')
```

## Do the number of revenue sources increases the amount of revenue generated.

```{r}
# plot the data
media_franchises_processed %>% 
  group_by(decade, franchise) %>% 
  summarise(n = n_distinct(franchise),
            revenue_sources = n_distinct(revenue_category),
            total_revenue = sum(revenue)) %>% 
  ggplot(aes(factor(revenue_sources), total_revenue)) +   
    geom_boxplot(aes(group=revenue_sources), notch=T) +
    scale_y_continuous(labels=dollar_format()) + 
    labs(x='Distinct Revenue Sources',
         y='Total Revenue (billion dollars)',
         title = 'Higher revenues are associated with a greater number of sources')

# plot a linear model - this is a poor fit, it's unlikely to be linear in nature.
media_franchises_processed %>% 
  group_by(decade, franchise) %>% 
  summarise(n = n_distinct(franchise),
            revenue_sources = n_distinct(revenue_category),
            total_revenue = sum(revenue)) %>% 
  lm(total_revenue ~ revenue_sources, data=.) %>% broom::tidy()
```

## What is the most lucrative form of revenue

```{r}
media_franchises_processed %>% 
  group_by(decade, `Revenue category`=fct_lump(revenue_category,4)) %>% 
  summarise(n = n_distinct(franchise),
            total_revenue = sum(revenue)) %>% 
  ggplot(aes(decade, total_revenue)) + 
    geom_line(aes(color=`Revenue category`)) +
    scale_y_continuous(labels=dollar_format()) + 
    labs(x='',
         y='Total Revenue (billion dollars)',
         title ='Merchandise is consistantly the highest grossing revenue') +
    theme(legend.position = c(0.25, 0.75))
```

